# Generated by Django 4.2.2 on 2024-04-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateTimeField(verbose_name='date_application')),
                ('telegram_id', models.IntegerField(verbose_name='telegram_id')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('first_name', models.CharField(max_length=64, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last_name')),
                ('date_joined', models.DateTimeField(verbose_name='date_joined')),
                ('device_type', models.CharField(max_length=96, verbose_name='device_type')),
                ('manufacturer', models.CharField(max_length=128, verbose_name='manufacturer')),
                ('model', models.CharField(max_length=128, verbose_name='application_model')),
                ('problem', models.TextField(verbose_name='application_problem')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='application_solution')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='application_price')),
            ],
            options={
                'db_table': 'view_application',
                'ordering': ['date_application'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewRefilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_refilling', models.DateTimeField(verbose_name='date_refilling')),
                ('telegram_id', models.IntegerField(verbose_name='telegram_id')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('first_name', models.CharField(max_length=64, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last_name')),
                ('date_joined', models.DateTimeField(verbose_name='date_joined')),
                ('model', models.CharField(max_length=128, verbose_name='refilling_model')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='refilling_price')),
            ],
            options={
                'db_table': 'view_refilling',
                'ordering': ['date_refilling'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_review', models.DateTimeField(verbose_name='date_review')),
                ('telegram_id', models.IntegerField(verbose_name='telegram_id')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('first_name', models.CharField(max_length=64, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last_name')),
                ('date_joined', models.DateTimeField(verbose_name='date_joined')),
                ('details', models.TextField(verbose_name='review_details')),
                ('rating', models.IntegerField(verbose_name='rating')),
            ],
            options={
                'db_table': 'view_review',
                'ordering': ['date_review'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type_title', models.CharField(max_length=128, unique=True, verbose_name='device_type_title')),
            ],
            options={
                'db_table': 'device_type',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_title', models.CharField(max_length=128, unique=True, verbose_name='manufacturer_title')),
            ],
            options={
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_review', models.DateTimeField(auto_now_add=True, verbose_name='date_review')),
                ('telegram_id', models.IntegerField(verbose_name='telegram_id')),
                ('details', models.TextField(verbose_name='review_details')),
                ('rating', models.IntegerField(verbose_name='rating')),
            ],
            options={
                'db_table': 'review',
                'ordering': ['date_review'],
                'indexes': [models.Index(fields=['date_review', 'telegram_id'], name='review_date_re_89c2cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Refilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_refilling', models.DateTimeField(auto_now_add=True, verbose_name='date_refilling')),
                ('telegram_id', models.IntegerField(verbose_name='telegram_id')),
                ('model', models.CharField(max_length=128, verbose_name='refilling_model')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='refilling_price')),
            ],
            options={
                'db_table': 'refilling',
                'ordering': ['date_refilling'],
                'indexes': [models.Index(fields=['date_refilling', 'telegram_id'], name='refilling_date_re_79d916_idx')],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_log', models.DateTimeField(auto_now_add=True, verbose_name='date_log')),
                ('telegram_id', models.IntegerField(verbose_name='telegram_id')),
                ('kind', models.CharField(max_length=64, verbose_name='log_kind')),
                ('event', models.TextField(verbose_name='log_event')),
            ],
            options={
                'db_table': 'log',
                'ordering': ['date_log'],
                'indexes': [models.Index(fields=['date_log', 'telegram_id'], name='log_date_lo_59ef00_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True, verbose_name='telegram_id')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('first_name', models.CharField(max_length=64, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last_name')),
                ('date_joined', models.DateTimeField(verbose_name='date_joined')),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['telegram_id'], name='customer_telegra_f5e35d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateTimeField(auto_now_add=True, verbose_name='date_application')),
                ('telegram_id', models.IntegerField(verbose_name='telegram_id')),
                ('device_type', models.CharField(max_length=96, verbose_name='device_type')),
                ('manufacturer', models.CharField(max_length=128, verbose_name='manufacturer')),
                ('model', models.CharField(max_length=128, verbose_name='application_model')),
                ('problem', models.TextField(verbose_name='application_problem')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='application_solution')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='application_price')),
            ],
            options={
                'db_table': 'application',
                'ordering': ['date_application'],
                'indexes': [models.Index(fields=['date_application', 'telegram_id'], name='application_date_ap_0a82d5_idx')],
            },
        ),
    ]
