# Generated by Django 4.2.2 on 2024-04-07 12:08

from pickle import FALSE, TRUE
from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from django.db import migrations
# Подключаем модуль для работы с датой/веременем
from datetime import datetime, timedelta
# Подключаем модкль генерации случайных чисел
import random

# Получение случайного ID телеграмм 9 цифр (например 611996998)
def get_telegram_id():
    telegram_id = ""
    for n in range(9):
        telegram_id = telegram_id + str(random.randint(0, 9)) 
    return telegram_id

# Получение случайного телефона
def get_telefon():
    if random.randint(0, 1) == 1:
        telefon = "+7-701-"
    else:
        telefon = "+7-705-" 
    telefon = telefon + str(random.randint(0, 9)) + str(random.randint(0, 9)) + str(random.randint(0, 9)) + "-" + str(random.randint(0, 9)) + str(random.randint(0, 9)) + str(random.randint(0, 9)) + str(random.randint(0, 9)) 
    return telefon

# Найти или Добавить Тип устройства
global dict_device_type
dict_device_type = {}

def get_device_type(apps, val):   
    # Поиск категории
    if val in dict_device_type.values():
        for k, v in dict_device_type.items():
            if v == val:
                return k    
    else:
        DeviceType = apps.get_model("customer", "DeviceType")
        device_type = DeviceType()
        device_type.device_type_title = val
        device_type.save()
        dict_device_type[device_type.id] = device_type.device_type_title
        return device_type.id
        
# Найти или Добавить Производители
global dict_manufacturer
dict_manufacturer = {}

def get_manufacturer(apps, val):   
    # Поиск категории
    if val in dict_manufacturer.values():
        for k, v in dict_manufacturer.items():
            if v == val:
                return k    
    else:
        Manufacturer = apps.get_model("customer", "Manufacturer")
        manufacturer = Manufacturer()
        manufacturer.manufacturer_title = val
        manufacturer.save()
        dict_manufacturer[manufacturer.id] = manufacturer.manufacturer_title
        return manufacturer.id
        

# Добавить Пользователи Telegram 
def insert_customer(apps, param):   
    Customer = apps.get_model("customer", "Customer")
    customer = Customer()
    customer.telegram_id = param[0]
    customer.phone_number = param[1]
    customer.first_name = param[2]
    customer.last_name = param[3]
    customer.date_joined = param[4]
    customer.save()
    return

# Добавить Заявку на ремонт
def insert_application(apps, param):   
    Application = apps.get_model("customer", "Application")
    application = Application()
    application.date_application = param[0]
    application.telegram_id = param[1]
    application.device_type = param[2]
    application.manufacturer = param[3]
    application.model = param[4]
    application.problem = param[5]
    application.solution = param[6]
    application.price = param[7]
    application.save()
    application.date_application = param[0]
    application.save()
    return

# Добавить Заявку на заправку картриджа
def insert_refilling(apps, param):   
    Refilling = apps.get_model("customer", "Refilling")
    refilling = Refilling()
    refilling.date_refilling = param[0]
    refilling.telegram_id = param[1]
    refilling.model = param[2]
    refilling.price = param[3]
    refilling.save()
    refilling.date_refilling = param[0]
    refilling.save()
    return

# Добавить Отзыв и оценку
def insert_review(apps, param):   
    Review = apps.get_model("customer", "Review")
    review = Review()
    review.date_review = param[0]
    review.telegram_id = param[1]
    review.details = param[2]
    review.rating = param[3]
    review.save()
    review.date_review = param[0]
    review.save()
    return

# Начальные данные 
def new_data(apps, schema_editor):
    try:
        # Суперпользователь id=1
        user = User.objects.create_superuser(username='root',
        email='service.bot.django@mail.ru',
        first_name='Руслан', 
        last_name='Кусаинов',
        password='SsNn5678+-@')
        print("Суперпользователь создан")
    
        # Группа менеджеров
        managers = Group.objects.get_or_create(name = 'Managers')
        managers = Group.objects.get(name='Managers')
        print("Группа менеджеров создана")
    
        # Пользователь с ролью менеджера id=2
        user = User.objects.create_user(username='manager', password='Ss0066+-', email='manager@mail.ru', first_name='Вадим', last_name='Куляев')
        managers.user_set.add(user)
        print("Менеджер добавлен в группу менеджеров")

        #ДРУГИЕ ФИО

        ## Простые пользователи () id3-12
        #user = User.objects.create_user(username='user1', password='Uu0066+-', email='user1@mail.ru', first_name='Динара', last_name='Махан')
        #user = User.objects.create_user(username='user2', password='Uu0066+-', email='user2@mail.ru', first_name='Алтыншаш ', last_name='Бабашева')
        #user = User.objects.create_user(username='user3', password='Uu0066+-', email='user3@mail.ru', first_name='Айман', last_name='Жалғасбаева')
        #user = User.objects.create_user(username='user4', password='Uu0066+-', email='user4@mail.ru', first_name='Амир', last_name='Дандамаев')
        #user = User.objects.create_user(username='user5', password='Uu0066+-', email='user5@mail.ru', first_name='Самат', last_name='Жұмабек')
        #user = User.objects.create_user(username='user6', password='Uu0066+-', email='user6@mail.ru', first_name='Камалбек', last_name='Көшербаев')
        #user = User.objects.create_user(username='user7', password='Uu0066+-', email='user7@mail.ru', first_name='Альбина', last_name='Алангузова')
        #user = User.objects.create_user(username='user8', password='Uu0066+-', email='user8@mail.ru', first_name='Жанел', last_name='Кабдуллина')
        #user = User.objects.create_user(username='user9', password='Uu0066+-', email='user9@mail.ru', first_name='Арман', last_name='Қайратов')
        #user = User.objects.create_user(username='user10', password='Uu0066+-', email='user10@mail.ru', first_name='Айдана ', last_name='Ермекова')        
        #print("Созданы простые пользователи")

        # Спавочники
        get_device_type(apps, "Принтер")
        get_device_type(apps, "Ксерокс")
        get_device_type(apps, "МФУ")
        get_device_type(apps, "Другое...")
        get_manufacturer(apps, "HP")
        get_manufacturer(apps, "Canon")
        get_manufacturer(apps, "Xerox")
        get_manufacturer(apps, "Pantum")
        get_manufacturer(apps, "Другое...")

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=90) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Ақгүл", "Сайлауова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP 1022", "Бумага не подается в принтер", "Исправлено", 2000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612", 1500 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=37) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612", 1500 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Привёз принтер, забрал через 4 дня. Сервис большой, много аппаратов на ремонте. Мастера чаще ан выездах, так что готовьтесь немного подождать, если везёте сами. ", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=88) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Есімхан", "Көмек", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP Color LaserJet Pro M252n", "При печати половина страницы белая", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "CF400A", 2000 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=37) + timedelta(minutes=random.randint(1, 360)), tel_id, "CF400A", 2000 ]		
        insert_refilling(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=87) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Ақбар", "Құрбанғали", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "МФУ", "HP", "МФУ HP LaserJet M111", "Принтер выдает черные страницы", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Вернули к жизни домашний МФУ. Гнал пустые листы и неожиданно застревал. Очень доволен. Всего лишь поменяли что-то. Работает, как новое.", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=86) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Султан", "Маратов", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Canon", "Canon 3104C007", "Бумага не подается в принтер", "Исправлено", 2500 ]		
        insert_application(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=84) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Айғаным", "Амантаева", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Xerox", "Xerox Phaser 6600DN", "Общая ошибка защиты принтера", "Исправлено", 4000 ]		
        insert_application(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=82) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Айдана", "Сәрсенова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP LaserJet Pro M404", "Принтер выдает черные страницы", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "CF259A", 1500 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Случайно уронили тяжёлую папку на стекло сканера и раскололи. Обратился в сервис - мастер заменил стекло и восстановил работоспособность аппарата. ", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=81) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Камилла", "Умарбекова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Ксерокс", "Canon", "Canon I-SENSYS MF3010", "Скрипит при печати", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=80) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Мейіржан", "Іздібеков", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP LaserJet M211d", "Бумага не подается в принтер", "Исправлено", 3500 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "C4096A", 2000 ]		
        insert_refilling(apps, parameters) 
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Оперативно выполнили ремонт.", 5 ]		
        insert_review(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Не ремонтируют струйные принтеры", 4 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=78) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Алмас", "Өтеген", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP LaserJet 1010", "Принтер выдает черные страницы", "Исправлено", 3500 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612A", 1500 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=37) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612A", 1500 ]		
        insert_refilling(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=77) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Алтынай", "Мұратбек", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "МФУ", "Canon", "Canon i-Sensys LBP-6030", "При печати половина страницы белая", "Исправлено", 3500 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "CE285A", 1200 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=37) + timedelta(minutes=random.randint(1, 360)), tel_id, "CE285A", 1200 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Обратился с тем, что при печати появлись полосы. Заменили фотобарабан. Работает отлично.", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=76) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Надира", "Тохтиева", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Canon", "Canon LBP112", "Бумага не подается в принтер", "Исправлено", 3500 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "CF217A", 1700 ]		
        insert_refilling(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=74) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Алия", "Сагадибекова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Xerox", "Xerox С230", "Принтер при печати выдает белые листы", "Исправлено", 3500 ]		
        insert_application(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=72) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Ержан", "Абдулла", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP 1022", "Принтер выдает черные страницы", "Исправлено", 2000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612", 1500 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Могу порекомендовать данный центр сервиса для ремонта офисных принтеров. Мастера перед выездом звонят. Аккуратно и чисто после ремонта.", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=71) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Әділхан", "Келесов", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Pantum", "Pantum P2502W", "Принтер при печати выдает белые листы", "Исправлено", 2000 ]		
        insert_application(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=70) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Молдир", "Рамазанова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "МФУ", "Canon", "Canon i-Sensys MF-453dw", "Скрипит при печати", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "CF259A", 1500 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Ремонт хорошо провели. Жаль, что нельзя день в день заказать.", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=68) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Дана", "Қизатуллина", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Другое...", "Samsung ML-3750", "Бумага не подается в принтер", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=66) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Даулет", "Ақашаев", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP Neverstop Laser 1000n", "Принтер при печати выдает белые листы", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "C4096A", 1500 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=37) + timedelta(minutes=random.randint(1, 360)), tel_id, "C4096A", 1500 ]		
        insert_refilling(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=64) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Аяжан", "Толегенова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Ксерокс", "Canon", "Canon i-Sensys MF-453dw", "Некачественные изображения", "Исправлено", 3000 ]		
        insert_application(apps, parameters)  
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Мастера хорошо знают своё дело. Вызывали в офис для диагностики и ремонта. Разные мастера приезжали, но сделали оба быстро. ", 5 ]		
        insert_review(apps, parameters)   
        
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=62) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Даулет", "Ақашаев", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP LaserJet 1320", "При печати половина страницы белая", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q5949A", 2500 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=37) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q5949A", 2500 ]		
        insert_refilling(apps, parameters)   
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=62) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Нұрболат", "Бахадыр", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Другое...", "HIPER P-1120", "Бумага не подается в принтер", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Не ремонтируют струйные принтеры", 4 ]		
        insert_review(apps, parameters)   
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=60) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Гүлнұр", "Жарболсын", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "МФУ", "HP", "HP LaserJet M111a", "Принтер выдает черные страницы", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Мастера нет, заправить некому, продать новый картридж тоже не могут, поскольку не знают цен", 4 ]		
        insert_review(apps, parameters)   
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=58) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Бағыжан", "Алпамыс", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Canon", "Canon LBP2900B", "Принтер при печати выдает белые листы", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612A", 1500 ]		
        insert_refilling(apps, parameters)   
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=56) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Миргул", "Мусакулова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Xerox", "Xerox Phaser 3160", "Принтер медленно печатает", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=53) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Мирас", "Қайыргелді", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Ксерокс", "Другое...", "Kyocera-Mita M2040dn", "Деформация бумаги при захвате", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Дорого, но надолго ремонт делают. Уже год принтер работает без нареканий. ", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=52) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Әйгерім", "Тілеумағанбетова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP 1022", "Принтер медленно печатает", "Исправлено", 2000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612", 1500 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=37) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612", 1500 ]		
        insert_refilling(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=50) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Әлибек", "Үшкемпір", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP Color LaserJet Pro M252n", "Принтер при печати выдает белые листы", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "CF400A", 2000 ]		
        insert_refilling(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=47) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Азиза", "Дабарова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "МФУ", "Pantum", "Pantum M6507W", "При печати половина страницы белая", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Периодически обращаемся с офсной техникой. Поломки, чистка. Пора оформлять годовое обслуживание.", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=46) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Аминат", "Берішбай", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Canon", "Canon 3104C007", "Принтер выдает черные страницы", "Исправлено", 2500 ]		
        insert_application(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=44) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Айым", "Аманкелдинова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Xerox", "Xerox Phaser 6600DN", "Принтер выдает черные страницы", "Исправлено", 4000 ]		
        insert_application(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=42) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Ғазиз", "Бекқұлы", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Ксерокс", "Другое...", "Brother DCP-1510E", "Принтер при печати выдает белые листы", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Привозил Ксерокс на диагностику. С проблемой бледной печати. Подлечили за час. Спасибо. ", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=40) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Аслан", "Қалеш", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP LaserJet M211d", "Бумага не подается в принтер", "Исправлено", 3500 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "C4096A", 2000 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=37) + timedelta(minutes=random.randint(1, 360)), tel_id, "C4096A", 2000 ]		
        insert_refilling(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=38) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Мұхаммеджан", "Арыстанов", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP LaserJet 1010", "Общая ошибка защиты принтера", "Исправлено", 3500 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612A", 1500 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=37) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612A", 1500 ]		
        insert_refilling(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=35) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Айдана", "Тлеуғажынова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "МФУ", "HP", "HP LaserJet M111a", "При печати половина страницы белая", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Решили проблему с МФУ, который останавливался в процессе печати. Всё работает, благодарю.", 5 ]		
        insert_review(apps, parameters)   
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=34) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Айбар", "Заманбеков", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Другое...", "Samsung ML-3750", "Принтер выдает черные страницы", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=32) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Аружан", "Дүйсен", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP Neverstop Laser 1000n", "Общая ошибка защиты принтера", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "C4096A", 1500 ]		
        insert_refilling(apps, parameters)  
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Про то, что они не звонят, как обещали через пару дней плсле того как забрали на ремонт, это правда. За это сняла одну звезду.. остальное было прекрасно", 4 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=30) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Айдана", "Тлеуғажынова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "МФУ", "Pantum", "Pantum M6507W", "Медленно печатает", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Всё работает, спасибо. ", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=28) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Арыстан", "Мұқашев", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP 1022", "При печати половина страницы белая", "Исправлено", 2000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612", 1500 ]		
        insert_refilling(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=25) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Арина", "Калыйбекова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP Color LaserJet Pro M252n", "Общая ошибка защиты принтера", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "CF400A", 2000 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Воспользовались услугами один раз и теперь этот сервисный центр у нас на постоянке. Быстро, удобно и нормально работают. ", 5 ]		
        insert_review(apps, parameters)   
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=24) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Айгерим", "Сергибаева", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Ксерокс", "Другое...", "Brother DCP-1510E", "Некачественные изображения", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=22) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Сымбат", "Усенбаева", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Canon", "Canon LBP2900B", "При печати половина страницы белая", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612A", 1500 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=17) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612A", 1500 ]		
        insert_refilling(apps, parameters)   
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=20) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Зауреш", "Бакбаева", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Xerox", "Xerox Phaser 3160", "Принтер выдает черные страницы", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Недалеко от офиса. Быстро приезжают. Иногда в день звонка.Приходили разные инженеры, но техника после всех работает хорошо. ", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=18) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Айжан", "Әлібек", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "МФУ", "Pantum", "Pantum P2518", "Не захватывает бумагу", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=16) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Валерия", "Верзакова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Xerox", "Xerox С230", "Принтер медленно печатает", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=14) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Асем ", "Бисимбаева", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Canon", "Canon LBP2900B", "При печати половина страницы белая", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612A", 1500 ]		
        insert_refilling(apps, parameters)   
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=12) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Нұртас", "Қасенов", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "МФУ", "HP", "HP LaserJet M111a", "Общая ошибка защиты принтера", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Ребята, спасибо! Спасли просто! Думал уже придётся готовить деньги на новый мфу. А так - послужит ещё годик! ", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=10) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Асель", "Каркенова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP 1022", "Бумага не подается в принтер", "Исправлено", 2000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612", 1500 ]		
        insert_refilling(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=8) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Диана", "Ергалиева", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP Color LaserJet Pro M252n", "При печати половина страницы белая", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "CF400A", 2000 ]		
        insert_refilling(apps, parameters)   
        parameters = [date1 + timedelta(days=7) + timedelta(minutes=random.randint(1, 360)), tel_id, "Обратилась по рекомендации знакомого. Мфу заработало в полном объеме спасибо. ", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=7) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Рамазан", "Сыздыков", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Ксерокс", "Другое...", "Brother DCP-1510E", "Принтер выдает черные страницы", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=6) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Анна", "Раздомина", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Canon", "Canon LBP2900B", "Принтер при печати выдает белые листы", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=5) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612A", 1500 ]		
        insert_refilling(apps, parameters)   
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=4) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Галымжан", "Жаналин", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "Xerox", "Xerox Phaser 3160", "Принтер медленно печатает", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=2) + timedelta(minutes=random.randint(1, 360)), tel_id, "Спасибо за быстрый ремонт моего Бразэра. Принтер бегает, как новый.", 5 ]		
        insert_review(apps, parameters)   

        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=2) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Куралай", "Кожагельдинова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Ксерокс", "Другое...", "Kyocera-Mita M2040dn", "Деформация бумаги при захвате", "Исправлено", 3000 ]		
        insert_application(apps, parameters)   
        
        # Пользователи Telegram и их заявки
        tel_id = get_telegram_id()
        date1 = datetime.now() - timedelta(days=1) + timedelta(minutes=random.randint(1, 360))
        parameters = [tel_id ,  get_telefon(), "Айдана", "Нурмухаметова", date1 ]		
        insert_customer(apps, parameters)   
        parameters = [date1, tel_id, "Принтер", "HP", "HP 1022", "Бумага не подается в принтер", "Исправлено", 2000 ]		
        insert_application(apps, parameters)   
        parameters = [date1 + timedelta(days=1) + timedelta(minutes=random.randint(1, 360)), tel_id, "Q2612", 1500 ]		
        insert_refilling(apps, parameters)   

    except Exception as error:
        print(error)

class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(new_data),
        migrations.RunSQL("""
CREATE VIEW view_application AS
SELECT application.id, application.date_application, application.telegram_id, customer.phone_number, customer.first_name, customer.last_name, customer.date_joined, application.device_type, application.manufacturer, application.model, application.problem, application.solution, application.price 
FROM application LEFT JOIN customer ON application.telegram_id=customer.telegram_id
ORDER BY application.date_application        
        """),
        migrations.RunSQL("""
CREATE VIEW view_refilling AS
SELECT refilling.id, refilling.date_refilling, refilling.telegram_id, customer.phone_number, customer.first_name, customer.last_name, customer.date_joined, refilling.model, refilling.price 
FROM refilling LEFT JOIN customer ON refilling.telegram_id=customer.telegram_id
ORDER BY refilling.date_refilling       
        """),
        migrations.RunSQL("""
CREATE VIEW view_review AS
SELECT review.id, review.date_review, review.telegram_id, customer.phone_number, customer.first_name, customer.last_name, customer.date_joined, review.details, review.rating 
FROM review LEFT JOIN customer ON review.telegram_id=customer.telegram_id
ORDER BY review.date_review 
"""),

    ]
